// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using partner_aluro.Data;

#nullable disable

namespace partneraluro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230123162449_NazwaFirmyAdres2Dostawy")]
    partial class NazwaFirmyAdres2Dostawy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("partner_aluro.Models.AddresPrestashop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("active")
                        .HasColumnType("int");

                    b.Property<string>("address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date_add")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("date_upd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted")
                        .HasColumnType("int");

                    b.Property<string>("dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id_address")
                        .HasColumnType("int");

                    b.Property<int?>("id_country")
                        .HasColumnType("int");

                    b.Property<int?>("id_customer")
                        .HasColumnType("int");

                    b.Property<int?>("id_manufacturer")
                        .HasColumnType("int");

                    b.Property<int?>("id_state")
                        .HasColumnType("int");

                    b.Property<int?>("id_supplier")
                        .HasColumnType("int");

                    b.Property<int?>("id_warehouse")
                        .HasColumnType("int");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vat_number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AddressPrestashop");
                });

            modelBuilder.Entity("partner_aluro.Models.Adress1rozliczeniowy", b =>
                {
                    b.Property<int>("Adres1rozliczeniowyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Adres1rozliczeniowyId"));

                    b.Property<string>("Adres1UserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataZakonczeniaDzialalnosci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Kraj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrLokalu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrNieruchomosci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Powiat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusNip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Vat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wojewodztwo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Adres1rozliczeniowyId");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("Adress1rozliczeniowy");
                });

            modelBuilder.Entity("partner_aluro.Models.Adress2dostawy", b =>
                {
                    b.Property<int>("Adres2dostawyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Adres2dostawyId"));

                    b.Property<string>("Adres2UserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kraj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaFirmy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Adres2dostawyId");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("Adress2dostawy");
                });

            modelBuilder.Entity("partner_aluro.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("Adress1rozliczeniowyId")
                        .HasColumnType("int");

                    b.Property<int?>("Adress2dostawyId")
                        .HasColumnType("int");

                    b.Property<bool?>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataZałożenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IdProfilDzialalnosci")
                        .HasColumnType("int");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NazwaFirmy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Newsletter")
                        .HasColumnType("bit");

                    b.Property<int?>("NewsletterID")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NotatkaOsobista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Nowy")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("PolitykaPrywatnosci")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Adress1rozliczeniowyId");

                    b.HasIndex("Adress2dostawyId");

                    b.HasIndex("IdUser");

                    b.HasIndex("NewsletterID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("partner_aluro.Models.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<string>("CartaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("RazemBrutto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RazemNetto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Zrealizowane")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dataPowstania")
                        .HasColumnType("datetime2");

                    b.HasKey("CartID");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("partner_aluro.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<string>("CartIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CartsCartID")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartsCartID");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("partner_aluro.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<bool?>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<int?>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaPlikuIkony")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("kolejnosc")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("partner_aluro.Models.ContactPrestashop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idcustommer")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("active")
                        .HasColumnType("int");

                    b.Property<DateTime?>("birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date_add")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("date_upd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id_default_group")
                        .HasColumnType("int");

                    b.Property<int?>("id_gender")
                        .HasColumnType("int");

                    b.Property<int?>("id_id_lang")
                        .HasColumnType("int");

                    b.Property<int?>("id_risk")
                        .HasColumnType("int");

                    b.Property<int?>("id_shop")
                        .HasColumnType("int");

                    b.Property<int?>("id_shop_group")
                        .HasColumnType("int");

                    b.Property<int?>("is_quest")
                        .HasColumnType("int");

                    b.Property<DateTime?>("newsletter_date_add")
                        .HasColumnType("datetime2");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("optin")
                        .HasColumnType("int");

                    b.Property<string>("passwd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secure_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactsPrestashop");
                });

            modelBuilder.Entity("partner_aluro.Models.ImageModel", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageNameCompress250x250")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageNameCompress645x410")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageSliderID")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImagesId")
                        .HasColumnType("int");

                    b.Property<int?>("SliderIds")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("fullPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("kolejnosc")
                        .HasColumnType("int");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pathImageCompress250x250")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pathImageCompress645x410")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("ImageSliderID");

                    b.HasIndex("ProductImagesId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("partner_aluro.Models.MetodyDostawy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SzczegolowyOpis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetodyDostawy");
                });

            modelBuilder.Entity("partner_aluro.Models.MetodyPlatnosci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SzczegolowyOpis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetodyPlatnosci");
                });

            modelBuilder.Entity("partner_aluro.Models.Newsletter", b =>
                {
                    b.Property<int>("NewsletterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsletterID"));

                    b.Property<string>("MessagerBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsletterID");

                    b.ToTable("Newsletter");
                });

            modelBuilder.Entity("partner_aluro.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdresDostawyInny")
                        .HasColumnType("bit");

                    b.Property<int>("AdressDostawyAdres2dostawyId")
                        .HasColumnType("int");

                    b.Property<string>("Komentarz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageToOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetodaDostawy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetodaPlatnosci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrZamowienia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RabatZamowienia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StanZamowienia")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("adresRozliczeniowyAdres1rozliczeniowyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdressDostawyAdres2dostawyId");

                    b.HasIndex("UserID");

                    b.HasIndex("adresRozliczeniowyAdres1rozliczeniowyId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("partner_aluro.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("partner_aluro.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<bool>("Bestseller")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CenaProduktuBrutto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CenaProduktuDetal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CenaProduktuNetto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CenaPromocyja")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataDodania")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EAN13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GlebokoscProduktu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GlebokoscWewnetrznaProduktu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ilosc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KrotkiOpis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materiał")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NazwaPlikuObrazka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaPromocyjna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pakowanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductImagesId")
                        .HasColumnType("int");

                    b.Property<bool>("Promocja")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<decimal?>("SzerokoscProduktu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SzerokoscWewnetrznaProduktu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Ukryty")
                        .HasColumnType("bit");

                    b.Property<decimal?>("WagaProduktu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Wymiar_wewnetrzny")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WysokoscProduktu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WysokoscWewnetrznaProduktu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("pathImageUrl250x250")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("partner_aluro.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductCategoryId");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("partner_aluro.Models.ProductNazwyPrestashop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("available_later")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("available_now")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description_short")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id_lang")
                        .HasColumnType("int");

                    b.Property<int?>("id_product")
                        .HasColumnType("int");

                    b.Property<int?>("id_shop")
                        .HasColumnType("int");

                    b.Property<string>("link_rewrite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meta_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meta_keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meta_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductsNamePrestashop");
                });

            modelBuilder.Entity("partner_aluro.Models.ProductPrestashop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("active")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("additional_shipping_cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte?>("advanced_stock_management")
                        .HasColumnType("tinyint");

                    b.Property<string>("available_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("available_for_order")
                        .HasColumnType("tinyint");

                    b.Property<int?>("cache_default_attribute")
                        .HasColumnType("int");

                    b.Property<byte?>("cache_has_attachments")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("cache_is_pack")
                        .HasColumnType("tinyint");

                    b.Property<int?>("condition")
                        .HasColumnType("int");

                    b.Property<byte?>("customizable")
                        .HasColumnType("tinyint");

                    b.Property<string>("date_add")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_upd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("depth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ean13")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<decimal?>("ecotax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("id_category_default")
                        .HasColumnType("int");

                    b.Property<int?>("id_manufacturer")
                        .HasColumnType("int");

                    b.Property<int?>("id_product")
                        .HasColumnType("int");

                    b.Property<int?>("id_product_redirected")
                        .HasColumnType("int");

                    b.Property<int?>("id_shop_default")
                        .HasColumnType("int");

                    b.Property<int?>("id_supplier")
                        .HasColumnType("int");

                    b.Property<int?>("id_tax_rules_group")
                        .HasColumnType("int");

                    b.Property<byte?>("indexed")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("is_virtual")
                        .HasColumnType("tinyint");

                    b.Property<string>("location")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("minimal_quantity")
                        .HasColumnType("int");

                    b.Property<byte?>("on_sale")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("online_only")
                        .HasColumnType("tinyint");

                    b.Property<int?>("out_of_stock")
                        .HasColumnType("int");

                    b.Property<int?>("pack_stock_type")
                        .HasColumnType("int");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<byte?>("quantity_discount")
                        .HasColumnType("tinyint");

                    b.Property<string>("reference")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte?>("show_price")
                        .HasColumnType("tinyint");

                    b.Property<string>("supplier_reference")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte?>("text_fields")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("unit_price_ratio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("unity")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("upc")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<byte?>("uploadable_files")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("visibility")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("wholesale_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProductsPrestashop");
                });

            modelBuilder.Entity("partner_aluro.Models.ProductQuantityPrestashop", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("depends_on_stock")
                        .HasColumnType("int");

                    b.Property<int>("id_product")
                        .HasColumnType("int");

                    b.Property<int>("id_product_attribute")
                        .HasColumnType("int");

                    b.Property<int>("id_shop")
                        .HasColumnType("int");

                    b.Property<int>("id_stock_available")
                        .HasColumnType("int");

                    b.Property<int>("out_of_stock")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ProductsQuantityPrestashop");
                });

            modelBuilder.Entity("partner_aluro.Models.ProfilDzialalnosci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaProfilu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rabat")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProfileDzialalnosci");
                });

            modelBuilder.Entity("partner_aluro.Models.SMS", b =>
                {
                    b.Property<int>("SMSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SMSId"));

                    b.Property<string>("apiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SMSId");

                    b.ToTable("SMS");
                });

            modelBuilder.Entity("partner_aluro.Models.Setting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingID"));

                    b.Property<string>("Platnosci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regulamin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SliderHome1")
                        .HasColumnType("int");

                    b.Property<int>("SliderHome2")
                        .HasColumnType("int");

                    b.Property<int>("SliderHome3")
                        .HasColumnType("int");

                    b.HasKey("SettingID");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("partner_aluro.Models.Slider", b =>
                {
                    b.Property<int>("ImageSliderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageSliderID"));

                    b.Property<int?>("IdObrazek")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageSliderID");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("partner_aluro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("partner_aluro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("partner_aluro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("partner_aluro.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("partner_aluro.Models.Adress1rozliczeniowy", b =>
                {
                    b.HasOne("partner_aluro.Models.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("partner_aluro.Models.Adress1rozliczeniowy", "UserID");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("partner_aluro.Models.Adress2dostawy", b =>
                {
                    b.HasOne("partner_aluro.Models.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("partner_aluro.Models.Adress2dostawy", "UserID");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("partner_aluro.Models.ApplicationUser", b =>
                {
                    b.HasOne("partner_aluro.Models.Adress1rozliczeniowy", "Adress1rozliczeniowy")
                        .WithMany()
                        .HasForeignKey("Adress1rozliczeniowyId");

                    b.HasOne("partner_aluro.Models.Adress2dostawy", "Adress2dostawy")
                        .WithMany()
                        .HasForeignKey("Adress2dostawyId");

                    b.HasOne("partner_aluro.Models.ProfilDzialalnosci", "ProfilDzialalnosci")
                        .WithMany("UserProfilDzialalnosci")
                        .HasForeignKey("IdUser");

                    b.HasOne("partner_aluro.Models.Newsletter", null)
                        .WithMany("Users")
                        .HasForeignKey("NewsletterID");

                    b.Navigation("Adress1rozliczeniowy");

                    b.Navigation("Adress2dostawy");

                    b.Navigation("ProfilDzialalnosci");
                });

            modelBuilder.Entity("partner_aluro.Models.Cart", b =>
                {
                    b.HasOne("partner_aluro.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("partner_aluro.Models.CartItem", b =>
                {
                    b.HasOne("partner_aluro.Models.Cart", "Carts")
                        .WithMany("CartItems")
                        .HasForeignKey("CartsCartID");

                    b.HasOne("partner_aluro.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carts");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("partner_aluro.Models.ImageModel", b =>
                {
                    b.HasOne("partner_aluro.Models.Slider", null)
                        .WithMany("ObrazkiDostepneWSliderze")
                        .HasForeignKey("ImageSliderID");

                    b.HasOne("partner_aluro.Models.Product", "Product")
                        .WithMany("Product_Images")
                        .HasForeignKey("ProductImagesId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("partner_aluro.Models.Order", b =>
                {
                    b.HasOne("partner_aluro.Models.Adress2dostawy", "AdressDostawy")
                        .WithMany()
                        .HasForeignKey("AdressDostawyAdres2dostawyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("partner_aluro.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("partner_aluro.Models.Adress1rozliczeniowy", "adresRozliczeniowy")
                        .WithMany()
                        .HasForeignKey("adresRozliczeniowyAdres1rozliczeniowyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdressDostawy");

                    b.Navigation("User");

                    b.Navigation("adresRozliczeniowy");
                });

            modelBuilder.Entity("partner_aluro.Models.OrderItem", b =>
                {
                    b.HasOne("partner_aluro.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("partner_aluro.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("partner_aluro.Models.Product", b =>
                {
                    b.HasOne("partner_aluro.Models.Category", "CategoryNavigation")
                        .WithMany("Produkty")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryNavigation");
                });

            modelBuilder.Entity("partner_aluro.Models.ProductCategory", b =>
                {
                    b.HasOne("partner_aluro.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("partner_aluro.Models.Product", "Product")
                        .WithMany("Kategorie")
                        .HasForeignKey("ProductID");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("partner_aluro.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("partner_aluro.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("partner_aluro.Models.Category", b =>
                {
                    b.Navigation("Produkty");
                });

            modelBuilder.Entity("partner_aluro.Models.Newsletter", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("partner_aluro.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("partner_aluro.Models.Product", b =>
                {
                    b.Navigation("Kategorie");

                    b.Navigation("Product_Images");
                });

            modelBuilder.Entity("partner_aluro.Models.ProfilDzialalnosci", b =>
                {
                    b.Navigation("UserProfilDzialalnosci");
                });

            modelBuilder.Entity("partner_aluro.Models.Slider", b =>
                {
                    b.Navigation("ObrazkiDostepneWSliderze");
                });
#pragma warning restore 612, 618
        }
    }
}
